/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#FFB000",
        "on-primary": "#4A2800",
        "on-secondary-fixed-variant": "#5C4300",
        "inverse-primary": "#A04100",
        "outline": "#A78B7E",
        "surface-container": "#291D17",
        "surface-variant": "#40322B",
        "secondary-fixed": "#FFDFA0",
        "on-secondary": "#402D00",
        "tertiary": "#AAC7FF",
        "on-primary-fixed-variant": "#7A3000",
        "led-green": "#22C55E",
        "surface-dim": "#1C110C",
        "secondary-fixed-dim": "#FBBC00",
        "on-tertiary-fixed": "#001B3E",
        "on-secondary-container": "#6D5000",
        "background-matte": "#1A1100",
        "on-error": "#690005",
        "error-container": "#93000A",
        "primary-fixed": "#FFDBCC",
        "surface-container-low": "#251913",
        "primary": "#FFB000",
        "border-graphite": "#332200",
        "outline-variant": "#584238",
        "terminal-dim": "#662B00",
        "on-tertiary-container": "#002958",
        "surface-container-high": "#342721",
        "tertiary-fixed-dim": "#AAC7FF",
        "background": "#1A1100",
        "on-primary-container": "#4B1B00",
        "on-primary-fixed": "#351000",
        "on-error-container": "#FFDAD6",
        "secondary": "#FFD000",
        "surface-container-highest": "#40322B",
        "on-tertiary": "#002F64",
        "tertiary-container": "#3E90FF",
        "inverse-surface": "#F5DED4",
        "inverse-on-surface": "#3B2D27",
        "on-surface": "#FFE066",
        "surface-container-lowest": "#160C07",
        "tertiary-fixed": "#D6E3FF",
        "surface-bright": "#443630",
        "surface": "#1A1100",
        "primary-fixed-dim": "#FFB693",
        "on-surface-variant": "#E0C0B2",
        "primary-container": "#EA6B1E",
        "error": "#FFB4AB",
        "led-red": "#EF4444",
        "on-secondary-fixed": "#261A00",
        "surface-steel": "#261A00",
        "secondary-container": "#FFB000",
        "on-background": "#F5DED4",
      },
      // Inter carries anything read as language; JetBrains Mono carries anything
      // read as instrumentation — labels, readouts, terminal output. Both have
      // far taller x-heights than IBM Plex, which is what buys legibility at
      // the small sizes this design depends on.
      fontFamily: {
        "display-lg": ["Inter", "system-ui", "sans-serif"],
        "title-sm": ["Inter", "system-ui", "sans-serif"],
        "body-base": ["Inter", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "system-ui", "sans-serif"],
        "status-tiny": ["JetBrains Mono", "ui-monospace", "monospace"],
        "mono-data": ["JetBrains Mono", "ui-monospace", "monospace"],
        "label-caps": ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      // Nothing sits below 12px. Line heights are looser than before because
      // the old 1.0-1.4 values were tuned for text too small to wrap much.
      fontSize: {
        "display-lg": ["34px", { lineHeight: "1.15", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["26px", { lineHeight: "1.25", fontWeight: "600" }],
        "title-sm": ["19px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-base": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "mono-data": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.3", letterSpacing: "0.06em", fontWeight: "600" }],
        "status-tiny": ["12px", { lineHeight: "1.3", letterSpacing: "0.04em", fontWeight: "500" }],
      },
      boxShadow: {
        'inset-bevel': 'inset 1px 1px 0px rgba(255, 255, 255, 0.1), inset -1px -1px 0px rgba(0, 0, 0, 0.8)',
        'outset-bevel': '1px 1px 0px rgba(255, 255, 255, 0.1), -1px -1px 0px rgba(0, 0, 0, 0.8)',
      },
      spacing: {
        "touch-target": "32px",
        "gutter": "16px",
        "panel-margin": "8px",
        "unit": "4px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
